# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'sainnhe/tmux-fzf'

# Use fish as default shell
set -g default-shell /usr/bin/fish

# True color settings
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

# Support for extended keys
set-window-option -g xterm-keys on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
set-option -gw xterm-keys on
set -gq allow-passthrough on
set -s  set-clipboard on

# Fix slow Esc key response
set -sg escape-time 10

# start window indexing from 1 instead of 0
set -g base-index 1

# start pane indexing from 1 instead of 0
setw -g pane-base-index 1

# re-number windows when one is closed
set -g renumber-windows on

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# Refresh tmux
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded"

# Enable mouse
set -g mouse on

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# =========================================================================================
# Bar Settings
set-option -g status-position top
set-option -g status-interval 1

set-option -g status-justify centre
set -g status-left-length 85
set -g status-style 'bg=default,fg=#f5e0dc'
set-option -g status-left '#[bg=#89b4fa , fg=#000000,bold]#(echo "  Session ")#[bg=#f9e2af , fg=#000000] #S #[fg=default,bg=default]#(" ") '
set-option -g status-right ' #[fg=#000000,bg=#f9e2af,bold]  %d %b, %Y #[fg=default,bg=default]#(" ") #[fg=#000000,bg=#89b4fa,bold] 󰥔 %H:%M:%S '

set -g window-status-format "#[fg=#000000,bg=#f38ba8]  #I #[fg=#000000,bg=#eba0ac] #W "
set -g window-status-current-format "#[fg=#000000,bg=#74c7ec,bold]  #I #[fg=#000000,bg=#89dceb,bold] #W "

set -g message-style bg=#f9e2af,fg=#1d1d1d,bold
set -g message-command-style bg=#1d1d1d,fg=#f9e2af,bold

set -g pane-active-border-style fg=#89dceb
set -g pane-border-style fg=#585b70
# =========================================================================================

set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
