[tools]
bat = "latest"
btop = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
jq = "latest"
jqp = "latest"
just = "latest"
lazygit = "latest"
neovim = "latest"
opentofu = "latest"
ripgrep = "latest"
scooter = "latest"
sd = "latest"
starship = "latest"
television = "latest"
tlrc = "latest"
tmux = "latest"
yazi = "latest"
yq = "latest"
zoxide = "latest"
"ubi:YS-L/csvlens" = "latest"
